image: Visual Studio 2017
platform: x64

environment:
  nodejs_version: "8"

  # increasing `meteor build` memory allocation
  # https://github.com/meteor/meteor/issues/9568
  TOOL_NODE_FLAGS: "--max-old-space-size=4096"
  TIMEOUT_SCALE_FACTOR: 8

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

init:
  # enabling RDP for debugging purposes
  - ps: $blockRdp = true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version

  # needed for meteor-dapp-wallet
  - git submodule update --init --recursive 

  # installs global dependencies
  - choco install meteor --params="'/RELEASE:1.8.1'"
  - choco install nsis
  - choco install 7zip

  - refreshenv
  - ps: refreshenv
 
  - node --version

  # prepare meteor-dapp-wallet
  #- cp config.example.json config.json
  - cd app && mkdir packages && cd packages
  - git clone https://github.com/EthersocialNetwork/meteor-package-tools && git clone https://github.com/EthersocialNetwork/meteor-package-elements
  - cd .. && yarn install
  - cd ..\..
  - cd

  - meteor --version
  # download 7za
  - curl -L http://www.7-zip.org/a/7z1900-extra.7z -o extra.7z
  - 7z.exe x extra.7z
  - copy x64\7za.exe "C:\\Program Files\\7-zip\\7za.exe"
  - copy "C:\\Program Files\\7-zip\\7za.exe" C:\Users\appveyor\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\bin\7z.exe && exit 0
  # fix console.js to show progress
  - cat C:\Users\appveyor\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\tools\console\console.js | sed "s@!this._stream.isTTY ||@@" > fix.js
  - copy fix.js C:\Users\appveyor\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\tools\console\console.js

build_script:
  - ps: |
      $env:METEOR_PROGRESS_DEBUG = 1
      cd app
      node_modules\.bin\meteor-build-client ..\test-build --path "" --verbose --debug
